version: "3.9"

x-shared-env: &shared-env
  REDIS_URL: redis://redis:6379/0

services:
  api:
    image: "horoscoper"
    restart: unless-stopped
    build: "."
    environment:
      <<: *shared-env
    ports:
      - 8080:8000

  worker:
    image: "horoscoper"
    restart: unless-stopped
    deploy:
      replicas: 2
    build: "."
    command:
      - python
      - -m
      - horoscoper.tasks.infer
    environment:
      <<: *shared-env
  
  redis:
    image: redis:7
    restart: unless-stopped
