{
 "title": "API",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   { "name": "path", "query": { "query": "label_values(path)" } }
  ]
 },
 "panels": [
  { "title": "API ($path)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "2xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{status_code=~\"2..\"}[$__interval]))",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Request duration, quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(starlette_request_duration_seconds_bucket{path=~\"$path\"}[$__interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(starlette_request_duration_seconds_bucket{path=\"$path\"}[$__interval])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(starlette_request_duration_seconds_bucket{path=\"$path\"}[$__interval])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "RPS by status code",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{path=~\"$path\"}[$__interval])) by (status_code)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "5xx",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(starlette_requests_total{status_code=~\"5..\"}[$__interval]))",
     "legendFormat": "0.95"
    }
   ]
  },
  { "title": "Infer SSE metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Total messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_infer_messages_count_total[$__interval]))",
     "legendFormat": "0.95"
    }
   ]
  },
  {
   "title": "Infer latency, quantile",
   "type": "timeseries",
   "description": "Time between request and the first response chunk in SSE",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(api_infer_first_response_bucket[$__interval])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(api_infer_first_response_bucket[$__interval])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(api_infer_first_response_bucket[$__interval])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Infer Message rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(api_infer_messages_count_total[$__interval])) by (status)",
     "legendFormat": "{{ status }}"
    }
   ]
  },
  {
   "title": "Error messages",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(api_infer_messages_count_total{status=\"ERROR\"}[$__interval]))",
     "legendFormat": "0.95"
    }
   ]
  },
  { "title": "Context batcher", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 } },
  {
   "title": "Avg bucket size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(context_batcher_batch_size_sum[$__range]) /rate(context_batcher_batch_size_count[$__range])"
    }
   ]
  },
  {
   "title": "Bucket size, quantile",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 3, "y": 19 },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(context_batcher_batch_size_bucket[2m])) by (le))",
     "legendFormat": "0.95"
    },
    {
     "expr": "histogram_quantile(0.75, sum(rate(context_batcher_batch_size_bucket[2m])) by (le))",
     "legendFormat": "0.75"
    },
    {
     "expr": "histogram_quantile(0.5, sum(rate(context_batcher_batch_size_bucket[2m])) by (le))",
     "legendFormat": "0.5"
    }
   ]
  },
  {
   "title": "Queue size",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 23 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "context_batcher_queue_size" }
   ]
  }
 ]
}