global:
  scrape_interval:     15s
  evaluation_interval: 15s

rule_files:
  # - "first.rules"
  # - "second.rules"

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['localhost:9090']
  - job_name: app
    scrape_interval: 5s
    static_configs:
      - targets: ['api:8000']
  - job_name: 'worker_exporter'
    scrape_interval: 5s
    static_configs:
      - targets:
        - worker_exporter:9726
